In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('/Users/shreyavora/Desktop/deliriumPaper/UCSFDelirium/Serial Transciptomics/Raw Data Files /serial_norm_gene_exp_df - serial_norm_gene_exp_df.csv')
data.head()

,Unnamed: 0,MVIR1.HS101.D0PBMC1.RSQ1,MVIR1.HS101.D21PBMC1.RSQ1,MVIR1.HS101.D4PBMC1.RSQ1,MVIR1.HS101.D7PBMC1.RSQ1,MVIR1.HS107.D0PBMC1.RSQ1,MVIR1.HS107.D14PBMC1.RSQ1,MVIR1.HS107.D21PBMC1.RSQ1,MVIR1.HS107.D28PBMC1.RSQ1,MVIR1.HS107.D4PBMC1.RSQ1,...,MVIR1.HS78.D7PBMC1.RSQ1,MVIR1.HS94.D0PBMC1.RSQ1,MVIR1.HS94.D14PBMC1.RSQ1,MVIR1.HS94.D21PBMC1.RSQ1,MVIR1.HS94.D28PBMC1.RSQ1,MVIR1.HS94.D4PBMC1.RSQ1,MVIR1.HS94.D7PBMC1.RSQ1,MVIR1.HS95.D0PBMC1.RSQ1,MVIR1.HS95.D4PBMC1.RSQ1,MVIR1.HS95.D7PBMC1.RSQ1
0,DPM1,9.383461,10.310383,10.375083,10.371731,9.310316,9.722012,9.738628,9.721323,9.265785,...,9.632137,9.060587,9.591066,9.598311,9.330273,9.642479,9.237258,9.545304,10.191289,10.122949
1,SCYL3,8.366948,7.956377,7.873112,7.121040,8.173659,7.989534,7.991571,7.978328,7.249722,...,7.835454,8.448783,7.956003,8.112171,7.451768,8.018165,8.081720,8.173131,8.146510,8.068521
2,C1orf112,7.891559,6.741496,7.468121,7.248001,7.445675,7.230942,7.540064,7.383477,6.734540,...,7.093991,7.681781,7.217095,7.189786,6.822362,7.412978,7.098533,7.229096,7.283772,6.917523
3,FGR,12.660471,14.552471,13.870511,13.819690,13.415327,14.077551,14.020591,14.039479,13.889838,...,14.221040,13.131565,14.167174,13.790594,13.384089,13.917705,13.805022,13.566704,13.354536,13.814906
4,CFH,7.387890,6.922546,7.497476,7.519009,7.035895,6.886334,6.813783,6.836159,6.535773,...,6.077664,7.418390,7.057395,6.988438,7.720554,7.297824,7.301619,6.412091,7.093077,7.285306

In [17]:
serial_annotation = pd.read_csv('/Users/shreyavora/Desktop/deliriumPaper/UCSFDelirium/Serial Transciptomics/Raw Data Files /serial_samples_annotation.csv')
serial_annotation_expression = pd.read_csv('/Users/shreyavora/Desktop/deliriumPaper/UCSFDelirium/Serial Transciptomics/Raw Data Files /serial_norm_gene_exp_df - serial_norm_gene_exp_df.csv', index_col=0)
serial_annotation.head()

,X,Subject,Day,Delirium,Diagnosis,Steroids,Late_del
0,MVIR1.HS101.D0PBMC1.RSQ1,101,0,1,1,0,0
1,MVIR1.HS101.D21PBMC1.RSQ1,101,21,2,1,0,0
2,MVIR1.HS101.D4PBMC1.RSQ1,101,4,0,1,0,0
3,MVIR1.HS101.D7PBMC1.RSQ1,101,7,0,1,0,0
4,MVIR1.HS107.D0PBMC1.RSQ1,107,7,0,1,0,1

In [18]:
serial_annotation = serial_annotation.drop(columns = ["Subject", "Day", "Diagnosis", "Late_del"])

In [19]:
serial_annotation['Delirium'] = (serial_annotation['Delirium'] > 0).astype(int)

In [20]:
serial_annotation.head()

                           X  Delirium  Steroids
0   MVIR1.HS101.D0PBMC1.RSQ1         1         0
1  MVIR1.HS101.D21PBMC1.RSQ1         1         0
2   MVIR1.HS101.D4PBMC1.RSQ1         0         0
3   MVIR1.HS101.D7PBMC1.RSQ1         0         0
4   MVIR1.HS107.D0PBMC1.RSQ1         0         0

In [27]:
X = serial_annotation_expression.transpose()
#X.head()
X = X.merge(serial_annotation, left_index=True, right_on='X', how='inner').set_index('X')
X.to_csv('serialGenes.csv', index=False)